### ISSUE TITLE
firebase

### ISSUE THREAD

**Issue by rabia06** [furqanyasin/Eatit2020#1]
Help me with the firebase please

**Comment by furqanyasin** [comment]
what is the problems you face?

**Comment by rabia06** [comment]
I don't know where to get the firebase data.

**Comment by furqanyasin** [comment]
first intigrate firebase and follow this series https://www.youtube.com/playlist?list=PLaoF-xhnnrRW4lXuIhNLhgVuYkIlF852V
see commits here with youtube videos related https://github.com/furqanyasin/Eatit2020/commits/master

**Comment by ShimwaHilary** [comment]
Hello sir, I have an issue with adding a restaurant when I  try to add it I get this message: object doesn't exist at the location. 
Any support, please!!
Thank
![Screenshot_20211002-075929](https://user-images.githubusercontent.com/68007525/135705548-36a52f85-a025-495f-aabb-79e7de46136b.png)
s.
